sudo: false
dist: trusty
language: python
python:
  - 3.6
before_install:
  - pip install requests
  - pip install paramiko
  - pip install simplejson
install:
  - python setup.py install
script:
  - sh travis/run_travis_tests.sh
