## -*- coding: utf-8 -*-
# 
# Copyright (c) 2016, Veritomyx, Inc.
#
# This file is part of the Python SDK for PeakInvestigator
# (http://veritomyx.com) and is distributed under the terms
# of the BSD 3-Clause license.

sudo: false
dist: trusty
language: python
python:
  - 3.6
before_install:
  - pip install requests
  - pip install paramiko
  - pip install simplejson
install:
  - python setup.py install
script:
  - sh travis/run_travis_tests.sh
